repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.9  # must match version in pyproject.toml
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  #- repo: https://github.com/pre-commit/mirrors-mypy
  #  rev: v1.7.0  # must match version in pyproject.toml
  #  hooks:
  #    - id: mypy
  #      additional_dependencies: [types-requests, types-PyYAML]
  #      exclude: "tests/|notebooks/"
