# Config to deploy Agent

# Deployment parameters
deployment:
  endpoint_name: telco-customer-support-agent
  scale_to_zero_enabled: true
  workload_size: Small  # Small, Medium, Large
  wait_for_ready: true

  # Optional: Budget policy ID
  # budget_policy_id: budget-policy-id

  # Optional: Additional deployment tags beyond defaults
  tags:
    project: telco_support_agent
    team: databricks-agents
    environment: dev

# Environment variables for the deployed agent
environment_vars:
  # any environment variables the agent might need
  # Example:
  # API_KEY: {{secrets/telco-support/api-key}}
  # DEBUG_MODE: false

# Agent Instructions - will be visible in the Review App
instructions: |
  Telco Customer Support Agent

  This agent helps with telecom customer support queries including:
  - Account information and subscription details
  - Billing inquiries and payment information
  - Technical support and troubleshooting
  - Product information and plan comparisons

  Please test various query types and provide feedback on response quality.

permissions:
  users:
    - telco-customer-support-dev
  permission_level: CAN_MANAGE  # CAN_VIEW, CAN_RUN, CAN_MANAGE
