# Config to deploy Agent

# Deployment parameters
deployment:
  endpoint_name: telco-customer-support-agent
  scale_to_zero_enabled: false
  workload_size: Small  # Small, Medium, Large
  wait_for_ready: true

  # Optional: Budget policy ID
  # budget_policy_id: budget-policy-id

  # Optional: Additional deployment tags beyond defaults
  tags:
    project: telco_support_agent
    team: databricks-agents
    environment: dev

# Cleanup old deployment versions
cleanup_old_versions: true
cleanup:
  keep_previous_count: 1  # Number of previous versions to keep (in addition to current)

# Monitoring config
monitoring:
  enabled: true
  replace_existing: false  # whether to replace existing monitors
  fail_on_error: false  # continue deployment if monitoring setup fails  

# Agent Instructions - will be visible in the Review App
instructions: |
  Telco Customer Support Agent

  This agent helps with telecom customer support queries including:
  - Account information and subscription details
  - Billing inquiries and payment information
  - Technical support and troubleshooting
  - Product information and plan comparisons

  Please test various query types and provide feedback on response quality.

permissions:
  - users:
      - telco-customer-support-prod
    permission_level: CAN_MANAGE
  - users:
      - telco-customer-support-dev
    permission_level: CAN_MANAGE
  - users:
      - users
    permission_level: CAN_RUN