# Config to deploy Agent

# UC model info
uc_model:
  catalog: "telco_customer_support_dev"
  schema: "agent"
  model_name: "supervisor_agent"

# Deployment parparamsameters
deployment:
  endpoint_name: "telco-support-agent"
  scale_to_zero_enabled: true
  workload_size: "Small"
  workload_type: "CPU"
