# Config for logging and registering agent
name: telco_customer_support_agent
description: "Multi-agent telco customer support system supervisor"

# MLflow logging params
input_example:
  input:
    - role: "user"
      content: "What plan am I currently on? My customer ID is CUS-10001."

# Unity Catalog registration params
uc_registration:
  catalog: "telco_customer_support_dev"
  schema: "agent"
  model_name: "telco_customer_support_agent"
  #alias: "prod"