# Config for logging and registering agent
name: telco_customer_support_agent
description: Multi-agent system for telco customer support

# MLflow logging params
input_example:
  input:
    - role: user
      content: What plan am I currently on?
  custom_inputs:
    customer: CUS-10001
