# Config for logging and registering agent
name: telco_customer_support_agent
description: "Multi-agent system for telco customer support"

# MLflow logging params
input_example:
  input:
    - role: "user"
      content: "My iPhone won't connect to international networks while traveling. How do I fix this?"

# Unity Catalog registration params
uc_registration:
  catalog: "telco_customer_support_dev"
  schema: "agent"
  model_name: "telco_customer_support_agent"
  #alias: "prod"