dev:
  data:
    catalog: telco_customer_support_prod
    schema: bronze
    indexes_schema: gold
  agent:
    catalog: telco_customer_support_dev
    schema: agent
    model_name: telco_customer_support_agent
    # permissions for UC functions
    permissions:
      groups:
        - telco-customer-support-dev
      privileges:
        - EXECUTE
staging:
  data:
    catalog: telco_customer_support_prod
    schema: bronze
    indexes_schema: gold
  agent:
    catalog: telco_customer_support_staging
    schema: agent
    model_name: telco_customer_support_agent
    # permissions for UC functions
    permissions:
      groups:
        - telco-customer-support-dev
      privileges:
        - EXECUTE
prod:
  data:
    catalog: telco_customer_support_prod
    schema: bronze
    indexes_schema: gold
  agent:
    catalog: telco_customer_support_prod
    schema: agent
    model_name: telco_customer_support_agent
    permissions:
      groups:
        - telco-customer-support-prod
      privileges:
        - EXECUTE
