dev:
  data:
    catalog: telco_customer_support_dev
    schema: bronze
  agent:
    catalog: telco_customer_support_dev
    schema: agent
    model_name: telco_customer_support_agent
prod:
  data:
    catalog: telco_customer_support_prod
    schema: bronze
  agent:
    catalog: telco_customer_support_prod
    schema: agent
    model_name: telco_customer_support_agent
