# Vector Search Config

environment:
  catalog: telco_customer_support_prod
  source_schema: gold
  agent_schema: agent

# Vector search endpoint
endpoint:
  name: telco-support-agent-vector-search
  type: STANDARD

# Embedding model configuration
embedding:
  model_endpoint: embeddings-text-large

indexes:
  knowledge_base:
    name: knowledge_base_index
    source_table: knowledge_base
    pipeline_type: TRIGGERED
    primary_key: kb_id
    embedding_source_column: formatted_content
    description: Vector search index for knowledge base articles, policies, FAQs, and guides
    columns_to_sync:
      - kb_id          
      - content         
      - title           
      - category        
      - subcategory     
      - content_type    
      - tags            
      - last_updated    
    test_queries:
      - unexpected charges on my bill
      - how to cancel service
      - international roaming fees

  support_tickets:
    name: support_tickets_index
    source_table: support_tickets
    pipeline_type: TRIGGERED
    primary_key: ticket_id
    embedding_source_column: formatted_content
    description: Vector search index for historical support tickets
    columns_to_sync:
      - ticket_id       
      - description    
      - customer_id    
      - category       
      - priority        
      - status         
      - resolution      
      - created_date   
      - resolved_date   
      - agent_id        
    test_queries:
      - phone won't connect to network
      - iPhone setup failed
      - can't make calls

# timeouts (in minutes)
timeouts:
  endpoint_creation: 10
  index_sync: 15
  status_check_interval: 0.5  # 30 seconds