name: Dev Databricks Infra CI/CD

on:
  push:
    branches:
      - manfred/adding_dabs
jobs:
  deploy:
    name: Deploy infra
    environment: dev
    env:
      DATABRICKS_CLIENT_ID: ${{secrets.DEV_DATABRICKS_CLIENT_ID}}
      DATABRICKS_CLIENT_SECRET: ${{secrets.DEV_DATABRICKS_CLIENT_SECRET}}
      DATABRICKS_BUNDLE_TARGET: dev
    runs-on:
      group: databricks-field-eng-protected-runner-group
      labels: linux-ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup databricks CLI
        uses: databricks/setup-cli@main
      - name: Validate Bundle for Dev
        id: validate
        run: |
          databricks bundle validate
      - name: Deploy Bundle to Dev
        id: deploy
        run: |
          databricks bundle deploy
