name: Staging - Deploy Databricks Resources

on:
  workflow_dispatch:
    inputs:
      deploy_ui:
        description: 'Force deploy UI app'
        required: false
        default: false
        type: boolean
  push:
    branches: ["main"]

jobs:
  deploy-staging:
    runs-on:
      group: databricks-field-eng-protected-runner-group
      labels: linux-ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"          
          
      - uses: databricks/setup-cli@main
  
      - name: Validate Bundle
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          echo "Validating bundle configuration..."
          databricks bundle validate -t staging

      - name: Deploy to Staging
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          echo "Deploying to staging environment..."
          databricks bundle deploy -t staging
          echo "Deployment to staging completed successfully"

      - name: Check for UI Changes
        id: ui-changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -E '^(telco_support_agent/ui/|resources/ui/customer_support_app\.yml)'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Deploy MCP Server
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          echo "Deploying MCP server..."
          databricks bundle run outage_info_mcp_server -t staging

      - name: Deploy UI App
        if: ${{ github.event.inputs.deploy_ui == 'true' || steps.ui-changes.outputs.changed == 'true' }}
        env:
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
          DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
        run: |
          echo "Deploying UI app..."
          databricks bundle run customer_support_ui -t staging

      - name: Post Deployment Summary
        if: always()
        run: |
          echo "## Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: Staging" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "- **UI Changes**: ${{ steps.ui-changes.outputs.changed == 'true' && 'Detected' || 'None' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Force UI Deploy**: ${{ github.event.inputs.deploy_ui == 'true' && 'Yes' || 'No' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **UI Deployed**: ${{ (github.event.inputs.deploy_ui == 'true' || steps.ui-changes.outputs.changed == 'true') && 'Yes' || 'No' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Ready for production deployment when release tag is created." >> $GITHUB_STEP_SUMMARY